### PR TITLE
New bib style

### PR DESCRIPTION
**Pull request by SaharMehrpour**
current: [https://devuxd.github.io/devx.cs.gmu.edu/publications/](https://devuxd.github.io/devx.cs.gmu.edu/publications/)
demo: [https://saharmehrpour.github.io/devx.cs.gmu.edu/publications/](https://saharmehrpour.github.io/devx.cs.gmu.edu/publications/)

I updated the publication page. 
To have a better styling, I created `bib.html` page with css file `bibliography.css`.
- We can use the `url` (or other custom) field in the bibtex for preprint versions, and create the doi links from `doi` fields. I used this design to do that.
- Right now, both doi and preprints have the same link.
- We can offer bibtex entries for each paper as well ([here](https://github.com/devuxd/devx.cs.gmu.edu/compare/master...SaharMehrpour:new-bib-page#diff-823a378b1720b2356a05e572e3f630e8R49)). Maybe we can show that in a pop-up window?

I removed the publication list for each member to simplify the process of adding papers. There is one inconsistency in my code:
- To create the links for author pages in the Publications page, I used the `bib_id` data value stored for each member. [here](https://github.com/devuxd/devx.cs.gmu.edu/compare/master...SaharMehrpour:new-bib-page?expand=1#diff-823a378b1720b2356a05e572e3f630e8R13)
- However, to list publications of each member in the member page, I had to query `first_name` and `last_name`. [here](https://github.com/devuxd/devx.cs.gmu.edu/compare/master...SaharMehrpour:new-bib-page?expand=1#diff-d99ea28b468f33dbd655419ea871a5acR53). I tried to use the `bib_id`, or other formats (e.g., "first_name last_name" or "last_name, first_name") but they didn't work.

### CODE REVIEW

**Comment by SaharMehrpour** [comment]
Alternatively, we can set `first_name` and `last_name` as names that appear in papers and have a normal `name` field that can be shown in the website and remove `bib_id`. For example, 
```
first_name: John H.
last_name: Doe-Smith
name: John Doe
```

**Comment by Alaboudi1** [comment]
I notice that members page has this pattern {{site.baseurl}}/members/{{first_name}}. can we do that using the author's first name instead of bib_id? I also prefer using the last name to avoid conflict with common first names.  Also, we may simply loop over all publications, and only include papers that match member's last_name on the member page. Of course, this sounds like not very optimized, but a solution that may work just fine.

**Comment by SaharMehrpour** [comment]
@Alaboudi1 
That is a valid point, and I thought about that too. Jekyll uses the file names to create URLs for members. So the pattern is more like `{{site.baseurl}}/members/{{fileName}}`. Right now, all file names are first names of members. We can change the file names to last names, which doesn't need any change in the implementation.

One point is about projects. The current implementation is incorrect. I am working on a new pull request with the following change in `_layouts/project.html`:
```
                <h3>Collaborators</h3>
                <div>
                    {% for collab in page.current_collaborators %}
                        {% for member in site.members %}
                            {% if member.key == collab %}
                            <div>
                                <div>
                                    <a href="{{ site.baseurl }}{{ member.url }}"><img
                                            src="{{ site.baseurl }}{{ member.image }}"></a>
                                </div>
                            </div>
                            {% endif %}
                        {% endfor %}
                    {% endfor %}
                </div>
```

**Comment by SaharMehrpour** [comment]
About the publications, I looked into the library that David added `Jekyll Scholar` which is also popular.  Here is the documentation: [https://github.com/inukshuk/jekyll-scholar](https://github.com/inukshuk/jekyll-scholar). The issues are also helpful in understanding the library.

It looks like [queries](https://github.com/inukshuk/jekyll-scholar#bibliography-filters) filter out bibitems based on conditions. However, the downside is the limited expressivity of queries. I am not sure how the queries are processed. I also couldn't figure out how we can iterate over bibitems manually (or even whether it is helpful or not). Please let me know if you found out.

**Issue**
If we only search based on the last names, isn't is possible that two people have the same last name? In this PR, it searches for both first names and last names. The problem is that the query looks for **"first_name"** and **"last_name"** instead of **"first_name last_name"**.  For example, consider the following case:

- member 1: John Doe
- member 2: John Smith
- member 3: Jane Doe
- publication authors: John Smith, Jane Doe 

The publication will appear for all 3 members which is incorrect. This situation may not happen, but maybe worth considering.

**Comment by SaharMehrpour** [comment]
I updated the style of some pages. Please check them out, and tell me what you think.
[https://saharmehrpour.github.io/devx.cs.gmu.edu/](https://saharmehrpour.github.io/devx.cs.gmu.edu/)

**Comment by Alaboudi1** [comment]
Thank you @SaharMehrpour for working on this! I have a question, do we need to have a project highlight page with collaborators and then members pages. I was wondering if we just merge this all together on the main page, would that be more concise? Instead of pointing to a member page of each collaborator, clicking on the collaborator will take you to the personal webpage. Something like amy ko website http://faculty.washington.edu/ajko/ . This is only a suggestion.

**Comment by SaharMehrpour** [comment]
I was thinking about having a different, kind of exciting, and non-static landing page. That's why I added carousels. Listing all projects on the Home page may be concise but is also ordinary. I also think having all projects in the Home page is more suitable for when the lab website is only a 'tab', as in Amy's website. Of course, it's my idea and we can certainly merge pages as you described. 

What do you think @luminaxster?

**Comment by luminaxster** [comment]
We should really state the user needs for the website: we have friction between social, personal, and academic layouts, and it is affecting the effectiveness of our presentation.
Since it is a research lab, we should not be the focus of the content, perhaps a short punchline about what we do and then immediately show news followed by the projects (we can add avatars as Amy does). We put ourselves and gallery photos at the end. I think news carousel works but not for research projects, they may be more effective in a grid.

**Comment by SaharMehrpour** [comment]
I revert all the changes other than the bib style from this PR to make it more focused.

**Review by luminaxster — APPROVED** [review]
Looking great =). let me know if you are done to merge it.

**Pull request merged**
